COLUMN log_mode FORMAT A20
SELECT log_mode FROM v$database;
ARCHIVE LOG LIST;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER PLUGGABLE DATABASE ALL OPEN;

COLUMN log_mode FORMAT A20
SELECT log_mode FROM v$database;
ARCHIVE LOG LIST;
