WHENEVER SQLERROR CONTINUE

DROP TABLE ventas PURGE;
DROP TABLE finanzas PURGE;
DROP TABLE inventario PURGE;
DROP TABLE rrhh PURGE;

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE ventas (
  id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha    DATE NOT NULL,
  cliente  VARCHAR2(100) NOT NULL,
  producto VARCHAR2(100) NOT NULL,
  monto    NUMBER(12, 2) NOT NULL
) TABLESPACE ventas;

CREATE INDEX idx_ventas ON ventas (fecha) TABLESPACE idx_ventas;

CREATE TABLE finanzas (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha  DATE NOT NULL,
  cuenta VARCHAR2(100) NOT NULL,
  tipo   VARCHAR2(20) NOT NULL,
  monto  NUMBER(12, 2) NOT NULL
) TABLESPACE finanzas;

CREATE INDEX idx_finanzas ON finanzas (fecha) TABLESPACE idx_finanzas;

CREATE TABLE inventario (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto       VARCHAR2(100) NOT NULL,
  cantidad       NUMBER NOT NULL,
  ubicacion      VARCHAR2(50) NOT NULL,
  actualizado_en DATE NOT NULL
) TABLESPACE inventario;

CREATE TABLE rrhh (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR2(100) NOT NULL,
  puesto        VARCHAR2(100) NOT NULL,
  salario       NUMBER(12, 2) NOT NULL,
  contratado_en DATE NOT NULL
) TABLESPACE rrhh;

INSERT INTO ventas (fecha, cliente, producto, monto)
SELECT
  SYSDATE - MOD(ROWNUM, 365),
  'Cliente ' || TO_CHAR(MOD(ROWNUM, 500)),
  'Producto ' || TO_CHAR(MOD(ROWNUM, 50)),
  ROUND(DBMS_RANDOM.VALUE(10, 5000), 2)
FROM dual CONNECT BY LEVEL <= 5000;

INSERT INTO finanzas (fecha, cuenta, tipo, monto)
SELECT
  SYSDATE - MOD(ROWNUM, 365),
  'Cuenta ' || TO_CHAR(MOD(ROWNUM, 20)),
  CASE MOD(ROWNUM, 2) WHEN 0 THEN 'INGRESO' ELSE 'EGRESO' END,
  ROUND(DBMS_RANDOM.VALUE(100, 20000), 2)
FROM dual CONNECT BY LEVEL <= 5000;

INSERT INTO inventario (producto, cantidad, ubicacion, actualizado_en)
SELECT
  'Producto ' || TO_CHAR(ROWNUM),
  TRUNC(DBMS_RANDOM.VALUE(0, 1000)),
  'Bodega ' || TO_CHAR(MOD(ROWNUM, 5) + 1),
  SYSDATE - MOD(ROWNUM, 30)
FROM dual CONNECT BY LEVEL <= 2000;

INSERT INTO rrhh (nombre, puesto, salario, contratado_en)
SELECT
  'Empleado ' || TO_CHAR(ROWNUM),
  CASE MOD(ROWNUM, 4)
    WHEN 0 THEN 'Analista'
    WHEN 1 THEN 'Supervisor'
    WHEN 2 THEN 'Tecnico'
    ELSE 'Asistente'
  END,
  ROUND(DBMS_RANDOM.VALUE(400000, 1800000), 2),
  SYSDATE - MOD(ROWNUM, 1000)
FROM dual CONNECT BY LEVEL <= 500;

COMMIT;

SELECT 'VENTAS' tabla, COUNT(*) filas FROM ventas
UNION ALL SELECT 'FINANZAS', COUNT(*) FROM finanzas
UNION ALL SELECT 'INVENTARIO', COUNT(*) FROM inventario
UNION ALL SELECT 'RRHH', COUNT(*) FROM rrhh;
