from dataclasses import dataclass

import oracledb

TABLAS = (
    "PARAMETRO",
    "BD_REGISTRADA",
    "PERFIL_BD",
    "ESTRATEGIA",
    "ESTRATEGIA_OBJETO",
    "TAREA",
    "PROGRAMACION",
    "SCRIPT_RMAN",
    "EJECUCION",
    "EJECUCION_PIEZA",
    "VERIFICACION",
    "ALERTA",
)

_DDL: tuple[str, ...] = (
    """
    CREATE TABLE parametro (
      clave   VARCHAR2(100) NOT NULL,
      valor   VARCHAR2(4000) NOT NULL,
      CONSTRAINT pk_parametro PRIMARY KEY (clave)
    )
    """,
    """
    CREATE TABLE bd_registrada (
      id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre        VARCHAR2(30) NOT NULL,
      oracle_home   VARCHAR2(400) NOT NULL,
      ambiente      VARCHAR2(20) NOT NULL,
      activa        CHAR(1) DEFAULT 'S' NOT NULL,
      creada_en     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT uq_bd_registrada_nombre UNIQUE (nombre),
      CONSTRAINT ck_bd_registrada_ambiente CHECK (ambiente IN ('PRODUCCION', 'PRUEBAS', 'DESARROLLO')),
      CONSTRAINT ck_bd_registrada_activa CHECK (activa IN ('S', 'N'))
    )
    """,
    """
    CREATE TABLE perfil_bd (
      id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      bd_id           NUMBER NOT NULL,
      log_mode        VARCHAR2(20) NOT NULL,
      contenido_json  CLOB NOT NULL,
      capturado_en    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_perfil_bd_bd FOREIGN KEY (bd_id) REFERENCES bd_registrada (id),
      CONSTRAINT ck_perfil_bd_log_mode CHECK (log_mode IN ('ARCHIVELOG', 'NOARCHIVELOG'))
    )
    """,
    """
    CREATE TABLE estrategia (
      id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      bd_id                       NUMBER NOT NULL,
      codigo                      VARCHAR2(20) NOT NULL,
      nombre                      VARCHAR2(200) NOT NULL,
      descripcion                 VARCHAR2(1000),
      prioridad                   VARCHAR2(10) NOT NULL,
      estado                      VARCHAR2(10) NOT NULL,
      version                     NUMBER DEFAULT 1 NOT NULL,
      creada_por                  VARCHAR2(100) NOT NULL,
      creada_en                   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      retencion_ventana_dias      NUMBER,
      retencion_redundancia       NUMBER,
      retencion_archivelog_dias   NUMBER,
      retencion_purga_automatica  CHAR(1) DEFAULT 'N' NOT NULL,
      CONSTRAINT fk_estrategia_bd FOREIGN KEY (bd_id) REFERENCES bd_registrada (id),
      CONSTRAINT uq_estrategia_bd_codigo UNIQUE (bd_id, codigo),
      CONSTRAINT ck_estrategia_prioridad CHECK (prioridad IN ('ALTA', 'MEDIA', 'BAJA')),
      CONSTRAINT ck_estrategia_estado CHECK (estado IN ('ACTIVA', 'INACTIVA')),
      CONSTRAINT ck_estrategia_purga CHECK (retencion_purga_automatica IN ('S', 'N')),
      CONSTRAINT ck_estrategia_retencion CHECK (
        retencion_ventana_dias IS NULL OR retencion_redundancia IS NULL
      )
    )
    """,
    """
    CREATE TABLE estrategia_objeto (
      id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      estrategia_id  NUMBER NOT NULL,
      tipo_objeto    VARCHAR2(20) NOT NULL,
      identificador  VARCHAR2(200),
      prioridad      VARCHAR2(10) NOT NULL,
      CONSTRAINT fk_estrategia_objeto_est FOREIGN KEY (estrategia_id) REFERENCES estrategia (id),
      CONSTRAINT ck_estrategia_objeto_tipo CHECK (tipo_objeto IN
        ('BASE_DATOS', 'PDB', 'TABLESPACE', 'DATAFILE', 'CONTROLFILE', 'SPFILE', 'ARCHIVELOG')),
      CONSTRAINT ck_estrategia_objeto_prioridad CHECK (prioridad IN ('ALTA', 'MEDIA', 'BAJA'))
    )
    """,
    """
    CREATE TABLE tarea (
      id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      estrategia_id         NUMBER NOT NULL,
      codigo                VARCHAR2(10) NOT NULL,
      tipo_respaldo         VARCHAR2(30) NOT NULL,
      modo_respaldo         VARCHAR2(15) NOT NULL,
      compresion            VARCHAR2(10) DEFAULT 'NINGUNA' NOT NULL,
      canales               NUMBER DEFAULT 1 NOT NULL,
      destino_ruta          VARCHAR2(400) NOT NULL,
      destino_etiqueta      VARCHAR2(100),
      omitir_solo_lectura   CHAR(1) DEFAULT 'N' NOT NULL,
      CONSTRAINT fk_tarea_estrategia FOREIGN KEY (estrategia_id) REFERENCES estrategia (id),
      CONSTRAINT uq_tarea_codigo UNIQUE (estrategia_id, codigo),
      CONSTRAINT ck_tarea_tipo CHECK (tipo_respaldo IN
        ('COMPLETO', 'INCREMENTAL_N0', 'INCREMENTAL_N1_DIFERENCIAL', 'INCREMENTAL_N1_ACUMULATIVO', 'ARCHIVELOG')),
      CONSTRAINT ck_tarea_modo CHECK (modo_respaldo IN ('AUTO', 'EN_LINEA', 'CONSISTENTE')),
      CONSTRAINT ck_tarea_compresion CHECK (compresion IN ('NINGUNA', 'BASIC', 'LOW', 'MEDIUM', 'HIGH')),
      CONSTRAINT ck_tarea_omitir CHECK (omitir_solo_lectura IN ('S', 'N'))
    )
    """,
    """
    CREATE TABLE programacion (
      id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tarea_id            NUMBER NOT NULL,
      tipo_frecuencia     VARCHAR2(15) NOT NULL,
      horas               VARCHAR2(200),
      dias_semana         VARCHAR2(50),
      intervalo_minutos   NUMBER,
      fecha_inicio        DATE,
      ventana_inicio      VARCHAR2(5),
      ventana_fin         VARCHAR2(5),
      zona_horaria        VARCHAR2(60) DEFAULT 'America/Costa_Rica' NOT NULL,
      politica_omision    VARCHAR2(25) DEFAULT 'EJECUTAR_EN_VENTANA' NOT NULL,
      CONSTRAINT fk_programacion_tarea FOREIGN KEY (tarea_id) REFERENCES tarea (id),
      CONSTRAINT uq_programacion_tarea UNIQUE (tarea_id),
      CONSTRAINT ck_programacion_frecuencia CHECK (tipo_frecuencia IN
        ('UNA_VEZ', 'INTERVALO', 'DIARIA', 'SEMANAL', 'MENSUAL')),
      CONSTRAINT ck_programacion_omision CHECK (politica_omision IN
        ('EJECUTAR_EN_VENTANA', 'OMITIR', 'EJECUTAR_SIEMPRE'))
    )
    """,
    """
    CREATE TABLE script_rman (
      id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tarea_id       NUMBER NOT NULL,
      version        NUMBER NOT NULL,
      contenido      CLOB NOT NULL,
      hash_sha256    VARCHAR2(64) NOT NULL,
      estado         VARCHAR2(15) DEFAULT 'BORRADOR' NOT NULL,
      aprobado_por   VARCHAR2(100),
      aprobado_en    TIMESTAMP,
      acepto_caida   CHAR(1) DEFAULT 'N' NOT NULL,
      motivo_rechazo VARCHAR2(1000),
      creado_en      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_script_rman_tarea FOREIGN KEY (tarea_id) REFERENCES tarea (id),
      CONSTRAINT uq_script_tarea_version UNIQUE (tarea_id, version),
      CONSTRAINT ck_script_rman_estado CHECK (estado IN ('BORRADOR', 'APROBADO', 'RECHAZADO', 'OBSOLETO')),
      CONSTRAINT ck_script_rman_acepto CHECK (acepto_caida IN ('S', 'N'))
    )
    """,
    """
    CREATE TABLE ejecucion (
      id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tarea_id            NUMBER NOT NULL,
      script_id           NUMBER NOT NULL,
      bd_id               NUMBER NOT NULL,
      programada_para     TIMESTAMP NOT NULL,
      inicio              TIMESTAMP,
      fin                 TIMESTAMP,
      estado              VARCHAR2(20) DEFAULT 'PROGRAMADA' NOT NULL,
      tipo_respaldo       VARCHAR2(30) NOT NULL,
      agente              VARCHAR2(64),
      ubicacion           VARCHAR2(400),
      archivos_generados  NUMBER,
      tamano_bytes        NUMBER,
      duracion_segundos   NUMBER,
      mensaje_rman        VARCHAR2(4000),
      errores             CLOB,
      advertencias        CLOB,
      estado_prueba       VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
      CONSTRAINT fk_ejecucion_tarea FOREIGN KEY (tarea_id) REFERENCES tarea (id),
      CONSTRAINT fk_ejecucion_script FOREIGN KEY (script_id) REFERENCES script_rman (id),
      CONSTRAINT fk_ejecucion_bd FOREIGN KEY (bd_id) REFERENCES bd_registrada (id),
      CONSTRAINT uq_ejecucion_tarea_hora UNIQUE (tarea_id, programada_para),
      CONSTRAINT ck_ejecucion_estado CHECK (estado IN
        ('PROGRAMADA', 'EN_CURSO', 'EXITOSA', 'CON_ADVERTENCIAS', 'FALLIDA', 'NO_EJECUTADA', 'BLOQUEADA', 'CANCELADA')),
      CONSTRAINT ck_ejecucion_prueba CHECK (estado_prueba IN ('PENDIENTE', 'OK', 'FALLIDA', 'NO_APLICA'))
    )
    """,
    "CREATE INDEX ix_ejecucion_estado ON ejecucion (estado, programada_para)",
    """
    CREATE TABLE ejecucion_pieza (
      id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ejecucion_id    NUMBER NOT NULL,
      nombre_archivo  VARCHAR2(400) NOT NULL,
      tamano_bytes    NUMBER,
      tag             VARCHAR2(30),
      vence_en        TIMESTAMP,
      obsoleta        CHAR(1) DEFAULT 'N' NOT NULL,
      CONSTRAINT fk_ejecucion_pieza_ejec FOREIGN KEY (ejecucion_id) REFERENCES ejecucion (id),
      CONSTRAINT ck_ejecucion_pieza_obsoleta CHECK (obsoleta IN ('S', 'N'))
    )
    """,
    """
    CREATE TABLE verificacion (
      id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ejecucion_id  NUMBER NOT NULL,
      tipo_prueba   VARCHAR2(30) NOT NULL,
      resultado     VARCHAR2(15) NOT NULL,
      detalle       CLOB,
      ejecutada_en  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_verificacion_ejec FOREIGN KEY (ejecucion_id) REFERENCES ejecucion (id),
      CONSTRAINT ck_verificacion_resultado CHECK (resultado IN ('PENDIENTE', 'OK', 'FALLIDA', 'NO_APLICA'))
    )
    """,
    """
    CREATE TABLE alerta (
      id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      codigo         VARCHAR2(40) NOT NULL,
      clave_dedup    VARCHAR2(200) NOT NULL,
      severidad      VARCHAR2(15) NOT NULL,
      estado         VARCHAR2(15) DEFAULT 'ABIERTA' NOT NULL,
      mensaje        VARCHAR2(2000) NOT NULL,
      bd_id          NUMBER,
      estrategia_id  NUMBER,
      tarea_id       NUMBER,
      ejecucion_id   NUMBER,
      abierta_en     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      resuelta_en    TIMESTAMP,
      CONSTRAINT fk_alerta_bd FOREIGN KEY (bd_id) REFERENCES bd_registrada (id),
      CONSTRAINT fk_alerta_estrategia FOREIGN KEY (estrategia_id) REFERENCES estrategia (id),
      CONSTRAINT fk_alerta_tarea FOREIGN KEY (tarea_id) REFERENCES tarea (id),
      CONSTRAINT fk_alerta_ejecucion FOREIGN KEY (ejecucion_id) REFERENCES ejecucion (id),
      CONSTRAINT ck_alerta_estado CHECK (estado IN ('ABIERTA', 'RECONOCIDA', 'RESUELTA'))
    )
    """,
    "CREATE INDEX ix_alerta_abierta ON alerta (estado, clave_dedup)",
)

_ORA_NO_EXISTE = 942


@dataclass(frozen=True)
class EstadoEsquema:
    instalado: bool
    tablas: dict[str, int]


def _eliminar_si_existe(cursor: oracledb.Cursor, tabla: str) -> None:
    try:
        cursor.execute(f"DROP TABLE {tabla} CASCADE CONSTRAINTS PURGE")
    except oracledb.Error as error:
        detalle = error.args[0] if error.args else None
        if getattr(detalle, "code", None) != _ORA_NO_EXISTE:
            raise


def instalar(conexion: oracledb.Connection) -> None:
    cursor = conexion.cursor()
    try:
        for tabla in reversed(TABLAS):
            _eliminar_si_existe(cursor, tabla)
        for sentencia in _DDL:
            cursor.execute(sentencia)
        conexion.commit()
    finally:
        cursor.close()


def desinstalar(conexion: oracledb.Connection) -> None:
    cursor = conexion.cursor()
    try:
        for tabla in reversed(TABLAS):
            _eliminar_si_existe(cursor, tabla)
        conexion.commit()
    finally:
        cursor.close()


def estado(conexion: oracledb.Connection) -> EstadoEsquema:
    cursor = conexion.cursor()
    try:
        cursor.execute(
            "SELECT table_name FROM user_tables WHERE table_name IN ({})".format(
                ",".join(f"'{t}'" for t in TABLAS)
            )
        )
        instaladas = {fila[0] for fila in cursor.fetchall()}
        if not instaladas:
            return EstadoEsquema(instalado=False, tablas={})
        conteos: dict[str, int] = {}
        for tabla in TABLAS:
            if tabla in instaladas:
                cursor.execute(f"SELECT COUNT(*) FROM {tabla}")
                conteos[tabla] = int(cursor.fetchone()[0])
        return EstadoEsquema(instalado=len(instaladas) == len(TABLAS), tablas=conteos)
    finally:
        cursor.close()
